"""
CritiqueMatrix schema — output of the Performance Critic Agent.
Contains the verdict, metrics from sandbox execution, and actionable feedback.
"""

from pydantic import BaseModel, Field
from typing import Optional, Literal


class CritiqueMatrix(BaseModel):
    """
    Structured critique of a proposed model architecture.
    Generated by the Critic agent after running the code in the sandbox.
    """

    status: Literal["APPROVE", "REJECT"] = Field(
        description="Final verdict: APPROVE if all constraints met, REJECT otherwise"
    )
    param_count: int = Field(
        description="Actual parameter count from sandbox execution"
    )
    mac_count: Optional[int] = Field(
        default=None,
        description="Actual MAC count from sandbox execution"
    )
    estimated_latency_ms: Optional[float] = Field(
        default=None,
        description="Estimated inference latency in milliseconds"
    )
    memory_usage_mb: Optional[float] = Field(
        default=None,
        description="Estimated GPU memory usage in MB"
    )

    # Constraint checks
    params_within_budget: bool = Field(
        description="Whether parameter count is within the user's max_params constraint"
    )
    latency_within_budget: Optional[bool] = Field(
        default=None,
        description="Whether latency is within the user's target_latency constraint"
    )

    # Feedback
    bottleneck_layer: Optional[str] = Field(
        default=None,
        description="The layer causing the most significant constraint violation"
    )
    reason: str = Field(
        description="Human-readable explanation of the verdict"
    )
    suggestion: Optional[str] = Field(
        default=None,
        description="Specific actionable suggestion for the Architect to fix the issue"
    )
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        description="Severity of the constraint violation"
    )

    # Code execution details
    code_executed_successfully: bool = Field(
        default=True,
        description="Whether the PyTorch code ran without errors in the sandbox"
    )
    execution_error: Optional[str] = Field(
        default=None,
        description="Error message if code execution failed"
    )
    sandbox_output: Optional[str] = Field(
        default=None,
        description="Raw stdout from the sandbox execution"
    )
